current_sql_server = "SQL Server"
current_sql_server_name = "LAPTOP-E5Q4G2L1"
current_data_base_name = "FISH_WORK"
current_bioanalis_table = "Register$"
current_age_struct_type_column = "litera"
current_age_struct_year_column = "litera"
current_age_struct_area_column = "litera"
