################################################################################
## Form generated from reading UI file 'ui_form.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1136, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(40, 30, 931, 461))
        self.tab_SQL_Base_connect = QWidget()
        self.tab_SQL_Base_connect.setObjectName(u"tab_SQL_Base_connect")
        self.btn_Connect_SQL_DB = QPushButton(self.tab_SQL_Base_connect)
        self.btn_Connect_SQL_DB.setObjectName(u"btn_Connect_SQL_DB")
        self.btn_Connect_SQL_DB.setGeometry(QRect(560, 150, 131, 51))
        self.label_SQL_Base_Name_2 = QLabel(self.tab_SQL_Base_connect)
        self.label_SQL_Base_Name_2.setObjectName(u"label_SQL_Base_Name_2")
        self.label_SQL_Base_Name_2.setGeometry(QRect(10, 10, 165, 59))
        font = QFont()
        font.setFamilies([u"Times New Roman"])
        font.setPointSize(12)
        font.setBold(True)
        self.label_SQL_Base_Name_2.setFont(font)
        self.label_SQL_Base_Name_2.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.label_SQL_Base_Name_2.setMargin(10)
        self.label_Text_SQL_Server_Name = QLabel(self.tab_SQL_Base_connect)
        self.label_Text_SQL_Server_Name.setObjectName(u"label_Text_SQL_Server_Name")
        self.label_Text_SQL_Server_Name.setGeometry(QRect(180, 10, 521, 59))
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(16)
        font1.setBold(True)
        self.label_Text_SQL_Server_Name.setFont(font1)
        self.label_Text_SQL_Server_Name.setStyleSheet(u"background-color: rgb(247, 247, 247);")
        self.label_Text_SQL_Server_Name.setMargin(10)
        self.label_SQL_Base_Name = QLabel(self.tab_SQL_Base_connect)
        self.label_SQL_Base_Name.setObjectName(u"label_SQL_Base_Name")
        self.label_SQL_Base_Name.setGeometry(QRect(10, 80, 161, 59))
        self.label_SQL_Base_Name.setFont(font)
        self.label_SQL_Base_Name.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.label_SQL_Base_Name.setMargin(10)
        self.label_Text_SQL_Base = QLabel(self.tab_SQL_Base_connect)
        self.label_Text_SQL_Base.setObjectName(u"label_Text_SQL_Base")
        self.label_Text_SQL_Base.setGeometry(QRect(180, 80, 521, 59))
        self.label_Text_SQL_Base.setFont(font1)
        self.label_Text_SQL_Base.setStyleSheet(u"background-color: rgb(247, 247, 247);")
        self.label_Text_SQL_Base.setMargin(10)
        self.label_Table_Name = QLabel(self.tab_SQL_Base_connect)
        self.label_Table_Name.setObjectName(u"label_Table_Name")
        self.label_Table_Name.setGeometry(QRect(10, 150, 150, 50))
        self.label_Table_Name.setFont(font)
        self.label_Table_Name.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.label_Table_Name.setMargin(10)
        self.label_Text_Table_Name = QLabel(self.tab_SQL_Base_connect)
        self.label_Text_Table_Name.setObjectName(u"label_Text_Table_Name")
        self.label_Text_Table_Name.setGeometry(QRect(180, 150, 300, 50))
        self.label_Text_Table_Name.setFont(font1)
        self.label_Text_Table_Name.setStyleSheet(u"background-color: rgb(247, 247, 247);")
        self.label_Text_Table_Name.setMargin(10)
        self.tabWidget.addTab(self.tab_SQL_Base_connect, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_Space_Name = QLabel(self.tab)
        self.label_Space_Name.setObjectName(u"label_Space_Name")
        self.label_Space_Name.setGeometry(QRect(10, 20, 150, 50))
        font2 = QFont()
        font2.setFamilies([u"Times New Roman"])
        font2.setPointSize(10)
        font2.setBold(True)
        self.label_Space_Name.setFont(font2)
        self.label_Space_Name.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.label_Space_Name.setMargin(10)
        self.label_Text_Space = QLabel(self.tab)
        self.label_Text_Space.setObjectName(u"label_Text_Space")
        self.label_Text_Space.setGeometry(QRect(140, 20, 300, 50))
        self.label_Text_Space.setFont(font1)
        self.label_Text_Space.setStyleSheet(u"background-color: rgb(247, 247, 247);")
        self.label_Text_Space.setMargin(10)
        self.label_Year = QLabel(self.tab)
        self.label_Year.setObjectName(u"label_Year")
        self.label_Year.setGeometry(QRect(10, 80, 151, 41))
        self.label_Year.setFont(font2)
        self.label_Year.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.label_Year.setMargin(10)
        self.label_Text_Year = QLabel(self.tab)
        self.label_Text_Year.setObjectName(u"label_Text_Year")
        self.label_Text_Year.setGeometry(QRect(170, 80, 100, 50))
        self.label_Text_Year.setFont(font1)
        self.label_Text_Year.setStyleSheet(u"background-color: rgb(247, 247, 247);")
        self.label_Text_Year.setMargin(10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1136, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_Connect_SQL_DB.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label_SQL_Base_Name_2.setText(QCoreApplication.translate("MainWindow", u"Server Name", None))
        self.label_Text_SQL_Server_Name.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_SQL_Base_Name.setText(QCoreApplication.translate("MainWindow", u"SQL DB", None))
        self.label_Text_SQL_Base.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_Table_Name.setText(QCoreApplication.translate("MainWindow", u"Table Name", None))
        self.label_Text_Table_Name.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SQL_Base_connect), QCoreApplication.translate("MainWindow", u"SQL DB", None))
        self.label_Space_Name.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0418\u0414 \u0412\u0411\u0420", None))
        self.label_Text_Space.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_Year.setText(QCoreApplication.translate("MainWindow", u"\u0413\u043e\u0434", None))
        self.label_Text_Year.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u0432\u0438\u0434\u0430", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u043c. \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0441\u0447\u0435\u0442 \u0432\u043e\u0437\u0440\u0430\u0441\u0442\u043d\u043e\u0439 \u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u044b", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u0411\u0438\u043e \u043f\u043e\u043a\u0430\u0437\u0430\u0442\u0435\u043b\u0438", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u043c.\u0440\u0430\u0439\u043e\u043d\u044b", None))
    # retranslateUi

